= Openshift Advanced Development Training - Homework

This Repository contains my Homework for the Advanced Openshift Training.

== Parks Map Multi-service Application

The Application consisting of three micro-services. These 
Services will be automatically installed into Openshift and run there as 
container based application.

=== Details

In this repository are three services:

* Two backend services providing geospatial data about Nationalparks and Major 
League Baseball park. The backend services are exposed as services with label 
"type=parksmap-backend". The data can be stored in a MongoDB database.
* A frontend parksmap application that can display the data on a map on a web 
site. The parksmap application dynamically discovers services with label 
"type=parksmap-backend".

There is also a directory "Infrastructure" which needs to contain scripts to set
up the entire homework environment from scratch as well as templates to create 
the various components. This directory contains place holders for all required 
scripts.

This Homework assignment will be graded by executing the pipeline at 
https://github.com/wkulhanek/advdev_homework_grading.

You can set up your own grading environment if you want to ensure that your 
submission will succeed.

